name: back test

on:
  - push
  - pull_request


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Étape 2 : Installer les dépendances
    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt install -y build-essential cmake qtbase5-dev qt5-qmake
        sudo apt-get install libgdal-dev

    # Étape 3 : Configurer et compiler le projet
    - name: Configure and Build
      run: |
        ls /home/runner/work/cute-gis
        mkdir -p ./build
        cd build
        cmake ../.. -DCMAKE_BUILD_TYPE=Release
        cmake --build . -- -j$(nproc)

    # Étape 4 : Exécuter les tests (si disponibles)
#    - name: Run Tests
#      run: |
#        cd build
#        ctest --output-on-failure

