name: Back Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check file structure
      run: |
        echo "Current directory:"
        pwd
        echo "Files in directory:"
        ls -R

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y build-essential cmake qt6-base-dev qt6-tools-dev-tools libgdal-dev


    - name: Configure and Build
      run: |
        mkdir -p cute-gis/build
        cmake -S cute-gis -B cute-gis/build -DCMAKE_BUILD_TYPE=Release
        cmake --build cute-gis/build -- -j$(nproc)
